server:
  port: 0

spring:
  application:
    name: assign-service
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      uri: http://localhost:8888

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring2?useSSL=false&useUnicode=false&serverTimezone=Asia/Seoul
    username: lshh
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#spring.jpa.properties.hibernate.format_sql=true

#Swagger path_pattern_parser not working

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER